//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const EmployeesTitle = () => {
  const record = useRecordContext();
  return <span>Employees {record ? `"${record.name}"` : ''}</span>;
};

export const EmployeesList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="name" />
      <DateField source="date" />
      <DateField source="time" />
      <ReferenceField source="machine" reference="Machines" />
      <NumberField source="production" />
      <NumberField source="frame" />
      <NumberField source="stitch" />
      <ImageField source="photo" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const EmployeesEdit = () => (
  <Edit title={<EmployeesTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="name" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="date" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="time" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="machine" reference="Machines" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="production" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="frame" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="stitch" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="photo" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const EmployeesCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="name" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="date" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="time" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="machine" reference="Machines" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="production" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="frame" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="stitch" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="photo" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  <ReferenceInput
    source="machine"
    label="machine"
    reference="Machines"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
];
