//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Employees: {
      name: 'Employees',
      fields: {
        name: 'Name',
        date: 'Date',
        time: 'Time',
        machine: 'Machine',
        production: 'Production',
        frame: 'Frame',
        stitch: 'Stitch',
        photo: 'Photo',
        id: 'id',
      },
    },
    InventoryItems: {
      name: 'Inventory Items',
      fields: { name: 'Name', quantity: 'Quantity', id: 'id' },
    },
    Machines: {
      name: 'Machines',
      fields: {
        machineName: 'Machine Name',
        status: 'Status',
        employee: 'Employee',
        work: 'Work',
        lastMaintainance: 'Last Maintainance',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Employees: {
      name: 'Employees (fr)',
      fields: {
        name: 'Name (fr)',
        date: 'Date (fr)',
        time: 'Time (fr)',
        machine: 'Machine (fr)',
        production: 'Production (fr)',
        frame: 'Frame (fr)',
        stitch: 'Stitch (fr)',
        photo: 'Photo (fr)',
        id: 'id',
      },
    },
    InventoryItems: {
      name: 'Inventory Items (fr)',
      fields: { name: 'Name (fr)', quantity: 'Quantity (fr)', id: 'id' },
    },
    Machines: {
      name: 'Machines (fr)',
      fields: {
        machineName: 'Machine Name (fr)',
        status: 'Status (fr)',
        employee: 'Employee (fr)',
        work: 'Work (fr)',
        lastMaintainance: 'Last Maintainance (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
